### ISSUE TITLE
Cannot build multicraft for ios,link error(irrlicht). (i am using mac intel core i9)

### ISSUE THREAD

**Issue by WILDDREAMER** [MoNTE48/Irrlicht#8]
Undefined symbols for architecture arm64:
  "_jpeg_CreateDecompress", referenced from:
      irr::video::CImageLoaderJPG::loadImage(irr::io::IReadFile) const in libIrrlicht.a(CImageLoaderJPG.o)
  "_jpeg_destroy_decompress", referenced from:
      irr::video::CImageLoaderJPG::loadImage(irr::io::IReadFile) const in libIrrlicht.a(CImageLoaderJPG.o)
  "_jpeg_finish_decompress", referenced from:
      irr::video::CImageLoaderJPG::loadImage(irr::io::IReadFile) const in libIrrlicht.a(CImageLoaderJPG.o)
  "_jpeg_read_header", referenced from:
      irr::video::CImageLoaderJPG::loadImage(irr::io::IReadFile) const in libIrrlicht.a(CImageLoaderJPG.o)
  "_jpeg_read_scanlines", referenced from:
      irr::video::CImageLoaderJPG::loadImage(irr::io::IReadFile) const in libIrrlicht.a(CImageLoaderJPG.o)
  "_jpeg_resync_to_restart", referenced from:
      irr::video::CImageLoaderJPG::loadImage(irr::io::IReadFile) const in libIrrlicht.a(CImageLoaderJPG.o)
  "_jpeg_start_decompress", referenced from:
      irr::video::CImageLoaderJPG::loadImage(irr::io::IReadFile) const in libIrrlicht.a(CImageLoaderJPG.o)
  "_jpeg_std_error", referenced from:
      irr::video::CImageLoaderJPG::loadImage(irr::io::IReadFile) const in libIrrlicht.a(CImageLoaderJPG.o)
...

**Comment by MoNTE48** [comment]
Hi. I don't think my fork is intended for production use at all.
I recommend using the official Irrlicht in your experiments.
